#pragma once
#define JOE_MOUSE_BUTTON_1         0
#define JOE_MOUSE_BUTTON_2         1
#define JOE_MOUSE_BUTTON_3         2
#define JOE_MOUSE_BUTTON_4         3
#define JOE_MOUSE_BUTTON_5         4
#define JOE_MOUSE_BUTTON_6         5
#define JOE_MOUSE_BUTTON_7         6
#define JOE_MOUSE_BUTTON_8         7
#define JOE_MOUSE_BUTTON_LAST      JOE_MOUSE_BUTTON_8
#define JOE_MOUSE_BUTTON_LEFT      JOE_MOUSE_BUTTON_1
#define JOE_MOUSE_BUTTON_RIGHT     JOE_MOUSE_BUTTON_2
#define JOE_MOUSE_BUTTON_MIDDLE    JOE_MOUSE_BUTTON_3